from fastapi import APIRouter
from app.api.v1 import auth, users, tenants, regulations, companies, compliance, chat, compliance_score, reports, tax_rates, report_analysis, analytics, report_templates, report_comments, notifications, audit_logs, hierarchy, balance_sheets, documents, dashboard

api_router = APIRouter()
api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(users.router, prefix="/users", tags=["users"])
api_router.include_router(tenants.router, prefix="/tenants", tags=["tenants"])
api_router.include_router(regulations.router, prefix="/regulations", tags=["regulations"])
api_router.include_router(companies.router, prefix="/companies", tags=["companies"])
api_router.include_router(compliance.router, prefix="/compliance", tags=["compliance"])
api_router.include_router(chat.router, prefix="/chat", tags=["chat"])
api_router.include_router(compliance_score.router, prefix="/compliance-score", tags=["compliance-score"])
api_router.include_router(reports.router, prefix="/reports", tags=["reports"])
api_router.include_router(tax_rates.router, prefix="/tax-rates", tags=["tax-rates"])
api_router.include_router(report_analysis.router, prefix="/report-analysis", tags=["report-analysis"])
api_router.include_router(analytics.router, prefix="/analytics", tags=["analytics"])
api_router.include_router(report_templates.router, prefix="/templates", tags=["templates"])
api_router.include_router(report_comments.router, prefix="/reports", tags=["comments"])
api_router.include_router(notifications.router, prefix="/notifications", tags=["notifications"])
api_router.include_router(audit_logs.router, prefix="/audit-logs", tags=["audit-logs"])
api_router.include_router(hierarchy.router, prefix="/hierarchy", tags=["hierarchy"])
api_router.include_router(balance_sheets.router, prefix="/balance-sheets", tags=["balance-sheets"])
api_router.include_router(documents.router, prefix="/documents", tags=["documents"])
api_router.include_router(dashboard.router, prefix="/dashboard", tags=["dashboard"])
