"""
Excel Export Service for Financial Balance Sheets and IFRS Transformations.
Generates an executive, Big-4 grade .xlsx workbook with:
1. Transformation Worksheet (3-way reconciliation: NAS / НСБУ -> Adjustments -> IFRS)
2. IFRS Statement of Financial Position (IAS 1 classified report)
3. Audit Journal (List of all debit/credit adjustments with standards)
"""
import io
from decimal import Decimal
from typing import Dict, Any, List
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

from app.db.models.balance_sheet import BalanceSheet, TransformedStatement, TransformationFormat


class ExcelExportService:
    @staticmethod
    def generate_reconciliation_workbook(balance_sheet: BalanceSheet) -> io.BytesIO:
        wb = Workbook()
        # Default sheet
        ws_recon = wb.active
        ws_recon.title = "Transformation Worksheet"

        # Styles definition
        navy_fill = PatternFill(start_color="1E293B", end_color="1E293B", fill_type="solid")
        navy_font = Font(color="FFFFFF", bold=True, size=11)

        header_fill = PatternFill(start_color="2563EB", end_color="2563EB", fill_type="solid")
        header_font = Font(color="FFFFFF", bold=True, size=10)

        section_fill = PatternFill(start_color="E2E8F0", end_color="E2E8F0", fill_type="solid")
        section_font = Font(color="0F172A", bold=True, size=10)

        total_fill = PatternFill(start_color="DCFCE7", end_color="DCFCE7", fill_type="solid")
        total_font = Font(color="166534", bold=True, size=11)

        discrepancy_fill = PatternFill(start_color="F0FDF4", end_color="F0FDF4", fill_type="solid")
        discrepancy_font = Font(color="15803D", bold=True, size=11)

        thin_side = Side(style="thin", color="CBD5E1")
        cell_border = Border(left=thin_side, right=thin_side, top=thin_side, bottom=thin_side)
        top_double_bottom_border = Border(
            top=Side(style="thin", color="64748B"),
            bottom=Side(style="double", color="0F172A"),
            left=thin_side,
            right=thin_side
        )

        company_name = balance_sheet.company.name if balance_sheet.company else "RegAI Organization"
        period_str = balance_sheet.period.strftime("%d.%m.%Y") if balance_sheet.period else "31.12.2024"

        # ----------------------------------------------------
        # SHEET 1: TRANSFORMATION WORKSHEET
        # ----------------------------------------------------
        ws_recon.views.sheetView[0].showGridLines = True

        # Header Title
        ws_recon.merge_cells("A1:H1")
        ws_recon["A1"] = f"{company_name.upper()} — STATUTORY (NAS / НСБУ) TO IFRS TRANSFORMATION WORKSHEET"
        ws_recon["A1"].font = Font(size=14, bold=True, color="1E293B")
        ws_recon["A1"].alignment = Alignment(horizontal="left", vertical="center")

        ws_recon.merge_cells("A2:H2")
        ws_recon["A2"] = f"Reporting Period: As of {period_str} | Generated by RegAI Compliance & Assurance Suite"
        ws_recon["A2"].font = Font(size=10, italic=True, color="64748B")

        # Table Column Headers
        headers = [
            ("A4", "Account Code", 14),
            ("B4", "Account / Line Item Description", 38),
            ("C4", "NAS / НСБУ Balance", 20),
            ("D4", "IFRS 16 (Leases)", 18),
            ("E4", "IAS 36 (Impairment)", 18),
            ("F4", "IFRS 9 (ECL Reserve)", 18),
            ("G4", "Other Adjustments", 18),
            ("H4", "IFRS / МСФО Balance", 20),
        ]

        for cell_coord, text, width in headers:
            col_letter = cell_coord[0]
            ws_recon[cell_coord] = text
            ws_recon[cell_coord].fill = navy_fill
            ws_recon[cell_coord].font = navy_font
            ws_recon[cell_coord].alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
            ws_recon.column_dimensions[col_letter].width = width

        ws_recon.row_dimensions[4].height = 28

        # Fetch transformed statements data if available
        ifrs_statement = next((s for s in balance_sheet.transformed_statements if s.format_type == TransformationFormat.IFRS), None)
        mcfo_statement = next((s for s in balance_sheet.transformed_statements if s.format_type == TransformationFormat.MCFO), None)

        # Categorize items
        items_by_cat = {"assets": [], "liabilities": [], "equity": []}
        for item in balance_sheet.items:
            cat = (item.category.value if hasattr(item.category, "value") else str(item.category or "assets")).lower()
            if cat in items_by_cat:
                items_by_cat[cat].append(item)
            else:
                items_by_cat["assets"].append(item)

        # Map adjustments by balance_sheet_item_id
        adj_by_item = {}
        global_adjs = []
        for adj in (balance_sheet.transformations or []):
            if adj.balance_sheet_item_id:
                adj_by_item.setdefault(str(adj.balance_sheet_item_id), []).append(adj)
            else:
                global_adjs.append(adj)

        curr_row = 5

        def write_category_section(cat_title: str, items: list, is_asset: bool):
            nonlocal curr_row
            ws_recon.merge_cells(f"A{curr_row}:H{curr_row}")
            sec_cell = ws_recon[f"A{curr_row}"]
            sec_cell.value = cat_title.upper()
            sec_cell.fill = section_fill
            sec_cell.font = section_font
            sec_cell.alignment = Alignment(horizontal="left", vertical="center")
            ws_recon.row_dimensions[curr_row].height = 20
            curr_row += 1

            start_cat_row = curr_row

            for item in items:
                row = curr_row
                ws_recon[f"A{row}"] = item.account_code or "—"
                ws_recon[f"B{row}"] = item.account_name
                ws_recon[f"C{row}"] = float(item.amount)

                # Break down adjustments for this item
                item_adjs = adj_by_item.get(str(item.id), [])
                ifrs16_val = 0.0
                ias36_val = 0.0
                ifrs9_val = 0.0
                other_val = 0.0

                for adj in item_adjs:
                    desc = (adj.description or "").lower()
                    amt = float(adj.adjustment_amount)
                    factor = 1.0 if (adj.adjustment_type == "debit" and is_asset) or (adj.adjustment_type == "credit" and not is_asset) else -1.0
                    signed_amt = amt * factor

                    if "ifrs 16" in desc or "lease" in desc or "аренд" in desc:
                        ifrs16_val += signed_amt
                    elif "ias 36" in desc or "impair" in desc or "обесцен" in desc:
                        ias36_val += signed_amt
                    elif "ifrs 9" in desc or "ecl" in desc or "резерв" in desc:
                        ifrs9_val += signed_amt
                    else:
                        other_val += signed_amt

                ws_recon[f"D{row}"] = ifrs16_val if ifrs16_val != 0 else ""
                ws_recon[f"E{row}"] = ias36_val if ias36_val != 0 else ""
                ws_recon[f"F{row}"] = ifrs9_val if ifrs9_val != 0 else ""
                ws_recon[f"G{row}"] = other_val if other_val != 0 else ""

                # Formula for IFRS balance: NAS + Sum of adjustments
                ws_recon[f"H{row}"] = f"=C{row}+SUM(D{row}:G{row})"

                # Styles
                ws_recon[f"A{row}"].alignment = Alignment(horizontal="center")
                for col in ["A", "B", "C", "D", "E", "F", "G", "H"]:
                    cell = ws_recon[f"{col}{row}"]
                    cell.border = cell_border
                    if col in ["C", "D", "E", "F", "G", "H"]:
                        cell.number_format = "#,##0.00;(#,##0.00);\"-\""
                        cell.alignment = Alignment(horizontal="right")

                curr_row += 1

            # Global adjustments applicable to this section
            for g_adj in global_adjs:
                g_desc = (g_adj.description or "").lower()
                g_amt = float(g_adj.adjustment_amount)
                matches_sec = False

                if is_asset and ("asset" in g_desc or "rou" in g_desc or "receivable" in g_desc or "дебитор" in g_desc or "ос" in g_desc):
                    matches_sec = True
                elif not is_asset and cat_title == "Liabilities" and ("liab" in g_desc or "обязательств" in g_desc or "кредит" in g_desc):
                    matches_sec = True
                elif not is_asset and cat_title == "Equity" and ("equity" in g_desc or "retained" in g_desc or "капитал" in g_desc or "прибыл" in g_desc):
                    matches_sec = True

                if matches_sec:
                    row = curr_row
                    ws_recon[f"A{row}"] = "ADJ"
                    ws_recon[f"B{row}"] = f"[IFRS Adjustment] {g_adj.description}"
                    ws_recon[f"C{row}"] = 0.0

                    if "ifrs 16" in g_desc or "lease" in g_desc:
                        ws_recon[f"D{row}"] = g_amt
                    elif "ias 36" in g_desc or "impair" in g_desc:
                        ws_recon[f"E{row}"] = -abs(g_amt)
                    elif "ifrs 9" in g_desc or "ecl" in g_desc:
                        ws_recon[f"F{row}"] = -abs(g_amt)
                    else:
                        ws_recon[f"G{row}"] = g_amt

                    ws_recon[f"H{row}"] = f"=C{row}+SUM(D{row}:G{row})"

                    for col in ["A", "B", "C", "D", "E", "F", "G", "H"]:
                        cell = ws_recon[f"{col}{row}"]
                        cell.border = cell_border
                        if col in ["C", "D", "E", "F", "G", "H"]:
                            cell.number_format = "#,##0.00;(#,##0.00);\"-\""
                            cell.alignment = Alignment(horizontal="right")
                    curr_row += 1

            # Category Sub-Total Row
            subtotal_row = curr_row
            ws_recon[f"A{subtotal_row}"] = ""
            ws_recon[f"B{subtotal_row}"] = f"TOTAL {cat_title.upper()}"
            ws_recon[f"B{subtotal_row}"].font = Font(bold=True)

            for col in ["C", "D", "E", "F", "G", "H"]:
                cell = ws_recon[f"{col}{subtotal_row}"]
                cell.value = f"=SUM({col}{start_cat_row}:{col}{subtotal_row-1})"
                cell.font = Font(bold=True)
                cell.fill = section_fill
                cell.number_format = "#,##0.00;(#,##0.00);\"-\""
                cell.border = top_double_bottom_border
                cell.alignment = Alignment(horizontal="right")

            ws_recon[f"A{subtotal_row}"].fill = section_fill
            ws_recon[f"B{subtotal_row}"].fill = section_fill
            ws_recon[f"A{subtotal_row}"].border = top_double_bottom_border
            ws_recon[f"B{subtotal_row}"].border = top_double_bottom_border

            curr_row += 2
            return subtotal_row

        asset_subtotal_row = write_category_section("Assets", items_by_cat["assets"], is_asset=True)
        liab_subtotal_row = write_category_section("Liabilities", items_by_cat["liabilities"], is_asset=False)
        equity_subtotal_row = write_category_section("Equity", items_by_cat["equity"], is_asset=False)

        # TOTAL EQUITY & LIABILITIES ROW
        tot_eq_liab_row = curr_row
        ws_recon[f"A{tot_eq_liab_row}"] = ""
        ws_recon[f"B{tot_eq_liab_row}"] = "TOTAL LIABILITIES & EQUITY"
        ws_recon[f"B{tot_eq_liab_row}"].font = total_font

        for col in ["C", "D", "E", "F", "G", "H"]:
            cell = ws_recon[f"{col}{tot_eq_liab_row}"]
            cell.value = f"={col}{liab_subtotal_row}+{col}{equity_subtotal_row}"
            cell.font = total_font
            cell.fill = total_fill
            cell.number_format = "#,##0.00;(#,##0.00);\"-\""
            cell.border = top_double_bottom_border
            cell.alignment = Alignment(horizontal="right")

        ws_recon[f"A{tot_eq_liab_row}"].fill = total_fill
        ws_recon[f"B{tot_eq_liab_row}"].fill = total_fill
        ws_recon[f"A{tot_eq_liab_row}"].border = top_double_bottom_border
        ws_recon[f"B{tot_eq_liab_row}"].border = top_double_bottom_border

        curr_row += 2

        # EQUILIBRIUM CHECK ROW (ZERO DELTA GUARD)
        check_row = curr_row
        ws_recon[f"A{check_row}"] = "✓"
        ws_recon[f"A{check_row}"].font = Font(bold=True, color="15803D")
        ws_recon[f"B{check_row}"] = "BALANCE SHEET EQUILIBRIUM DISCREPANCY (Assets - Eq & Liab)"
        ws_recon[f"B{check_row}"].font = discrepancy_font

        for col in ["C", "H"]:
            cell = ws_recon[f"{col}{check_row}"]
            cell.value = f"={col}{asset_subtotal_row}-{col}{tot_eq_liab_row}"
            cell.font = discrepancy_font
            cell.fill = discrepancy_fill
            cell.number_format = "$#,##0.00;($#,##0.00);\"$0.00 (BALANCED)\""
            cell.border = cell_border
            cell.alignment = Alignment(horizontal="right")

        ws_recon[f"A{check_row}"].fill = discrepancy_fill
        ws_recon[f"B{check_row}"].fill = discrepancy_fill
        ws_recon[f"A{check_row}"].border = cell_border
        ws_recon[f"B{check_row}"].border = cell_border

        # ----------------------------------------------------
        # SHEET 2: IFRS STATEMENT OF FINANCIAL POSITION
        # ----------------------------------------------------
        ws_ifrs = wb.create_sheet(title="IFRS Balance Sheet")
        ws_ifrs.views.sheetView[0].showGridLines = True

        ws_ifrs.merge_cells("A1:C1")
        ws_ifrs["A1"] = f"{company_name.upper()} — STATEMENT OF FINANCIAL POSITION (IFRS / МСФО)"
        ws_ifrs["A1"].font = Font(size=14, bold=True, color="1E293B")

        ws_ifrs.merge_cells("A2:C2")
        ws_ifrs["A2"] = f"Presented in accordance with IAS 1 'Presentation of Financial Statements' as of {period_str}"
        ws_ifrs["A2"].font = Font(size=10, italic=True, color="64748B")

        ws_ifrs["A4"] = "Line Item (IFRS Classification)"
        ws_ifrs["B4"] = "Note / Standard"
        ws_ifrs["C4"] = f"As of {period_str}"

        for col, width in [("A", 48), ("B", 24), ("C", 22)]:
            ws_ifrs.column_dimensions[col].width = width

        ws_ifrs["A4"].fill = navy_fill
        ws_ifrs["B4"].fill = navy_fill
        ws_ifrs["C4"].fill = navy_fill
        ws_ifrs["A4"].font = navy_font
        ws_ifrs["B4"].font = navy_font
        ws_ifrs["C4"].font = navy_font
        ws_ifrs.row_dimensions[4].height = 24

        r2 = 5
        if ifrs_statement and isinstance(ifrs_statement.transformed_data, dict):
            st = ifrs_statement.transformed_data.get("statement_of_financial_position", {})

            def write_ifrs_group(group_title: str, items_dict: dict, total_amt: float):
                nonlocal r2
                ws_ifrs[f"A{r2}"] = group_title.upper()
                ws_ifrs[f"A{r2}"].font = Font(bold=True, color="1E293B")
                ws_ifrs[f"A{r2}"].fill = section_fill
                ws_ifrs[f"B{r2}"].fill = section_fill
                ws_ifrs[f"C{r2}"].fill = section_fill
                r2 += 1

                for sub_key, sub_items in items_dict.items():
                    if sub_key == "total" or not isinstance(sub_items, list) or len(sub_items) == 0:
                        continue
                    sub_title = sub_key.replace("_", " ").title()
                    sub_total = sum(float(i.get("amount", 0)) for i in sub_items)
                    ws_ifrs[f"A{r2}"] = f"  {sub_title}"
                    ws_ifrs[f"B{r2}"] = "IAS 1 / IFRS"
                    ws_ifrs[f"C{r2}"] = sub_total
                    ws_ifrs[f"C{r2}"].number_format = "#,##0.00;(#,##0.00);\"-\""
                    ws_ifrs[f"C{r2}"].alignment = Alignment(horizontal="right")
                    ws_ifrs[f"A{r2}"].border = cell_border
                    ws_ifrs[f"B{r2}"].border = cell_border
                    ws_ifrs[f"C{r2}"].border = cell_border
                    r2 += 1

                # Group total
                ws_ifrs[f"A{r2}"] = f"Total {group_title}"
                ws_ifrs[f"A{r2}"].font = Font(bold=True)
                ws_ifrs[f"C{r2}"] = total_amt
                ws_ifrs[f"C{r2}"].font = Font(bold=True)
                ws_ifrs[f"C{r2}"].number_format = "#,##0.00;(#,##0.00);\"-\""
                ws_ifrs[f"C{r2}"].alignment = Alignment(horizontal="right")
                ws_ifrs[f"A{r2}"].border = top_double_bottom_border
                ws_ifrs[f"B{r2}"].border = top_double_bottom_border
                ws_ifrs[f"C{r2}"].border = top_double_bottom_border
                r2 += 2

            assets = st.get("assets", {})
            nc_assets = assets.get("non_current_assets", {})
            c_assets = assets.get("current_assets", {})
            write_ifrs_group("Non-Current Assets", nc_assets, float(nc_assets.get("total", 0)))
            write_ifrs_group("Current Assets", c_assets, float(c_assets.get("total", 0)))

            # TOTAL ASSETS
            ws_ifrs[f"A{r2}"] = "TOTAL ASSETS"
            ws_ifrs[f"A{r2}"].font = total_font
            ws_ifrs[f"A{r2}"].fill = total_fill
            ws_ifrs[f"B{r2}"].fill = total_fill
            ws_ifrs[f"C{r2}"] = float(assets.get("total", 0))
            ws_ifrs[f"C{r2}"].font = total_font
            ws_ifrs[f"C{r2}"].fill = total_fill
            ws_ifrs[f"C{r2}"].number_format = "#,##0.00;(#,##0.00);\"-\""
            ws_ifrs[f"C{r2}"].alignment = Alignment(horizontal="right")
            ws_ifrs[f"A{r2}"].border = top_double_bottom_border
            ws_ifrs[f"B{r2}"].border = top_double_bottom_border
            ws_ifrs[f"C{r2}"].border = top_double_bottom_border
            r2 += 2

            eq_liab = st.get("equity_and_liabilities", {})
            equity = eq_liab.get("equity", {})
            nc_liab = eq_liab.get("non_current_liabilities", {})
            c_liab = eq_liab.get("current_liabilities", {})
            write_ifrs_group("Equity", equity, float(equity.get("total", 0)))
            write_ifrs_group("Non-Current Liabilities", nc_liab, float(nc_liab.get("total", 0)))
            write_ifrs_group("Current Liabilities", c_liab, float(c_liab.get("total", 0)))

            # TOTAL EQUITY AND LIABILITIES
            ws_ifrs[f"A{r2}"] = "TOTAL EQUITY AND LIABILITIES"
            ws_ifrs[f"A{r2}"].font = total_font
            ws_ifrs[f"A{r2}"].fill = total_fill
            ws_ifrs[f"B{r2}"].fill = total_fill
            ws_ifrs[f"C{r2}"] = float(eq_liab.get("total", 0))
            ws_ifrs[f"C{r2}"].font = total_font
            ws_ifrs[f"C{r2}"].fill = total_fill
            ws_ifrs[f"C{r2}"].number_format = "#,##0.00;(#,##0.00);\"-\""
            ws_ifrs[f"C{r2}"].alignment = Alignment(horizontal="right")
            ws_ifrs[f"A{r2}"].border = top_double_bottom_border
            ws_ifrs[f"B{r2}"].border = top_double_bottom_border
            ws_ifrs[f"C{r2}"].border = top_double_bottom_border

        # ----------------------------------------------------
        # SHEET 3: AUDIT ADJUSTMENTS JOURNAL
        # ----------------------------------------------------
        ws_audit = wb.create_sheet(title="Audit Adjustments Log")
        ws_audit.views.sheetView[0].showGridLines = True

        ws_audit.merge_cells("A1:F1")
        ws_audit["A1"] = f"{company_name.upper()} — AUDIT ADJUSTMENTS & RECLASSIFICATION JOURNAL"
        ws_audit["A1"].font = Font(size=14, bold=True, color="1E293B")

        audit_headers = [
            ("A3", "#", 6),
            ("B3", "Standard / Category", 24),
            ("C3", "Adjustment Description", 45),
            ("D3", "Entry Type", 14),
            ("E3", "Amount (Reporting CCY)", 22),
            ("F3", "Target Balance Sheet Account", 30),
        ]

        for cell_coord, text, width in audit_headers:
            col_letter = cell_coord[0]
            ws_audit[cell_coord] = text
            ws_audit[cell_coord].fill = navy_fill
            ws_audit[cell_coord].font = navy_font
            ws_audit[cell_coord].alignment = Alignment(horizontal="center", vertical="center")
            ws_audit.column_dimensions[col_letter].width = width

        ws_audit.row_dimensions[3].height = 24

        r3 = 4
        all_adjs = list(balance_sheet.transformations or [])
        if all_adjs:
            for idx, adj in enumerate(all_adjs, start=1):
                ws_audit[f"A{r3}"] = idx
                ws_audit[f"A{r3}"].alignment = Alignment(horizontal="center")
                ws_audit[f"B{r3}"] = adj.ifrs_category or "IFRS General"
                ws_audit[f"C{r3}"] = adj.description
                ws_audit[f"D{r3}"] = adj.adjustment_type.upper()
                ws_audit[f"D{r3}"].alignment = Alignment(horizontal="center")
                ws_audit[f"E{r3}"] = float(adj.adjustment_amount)
                ws_audit[f"E{r3}"].number_format = "#,##0.00;(#,##0.00);\"-\""
                ws_audit[f"E{r3}"].alignment = Alignment(horizontal="right")
                ws_audit[f"F{r3}"] = adj.balance_sheet_item.account_name if adj.balance_sheet_item else "Global Equity / Reserve Impact"

                for col in ["A", "B", "C", "D", "E", "F"]:
                    ws_audit[f"{col}{r3}"].border = cell_border
                r3 += 1

            # Total adjustments sum
            ws_audit[f"C{r3}"] = "TOTAL ADJUSTMENTS"
            ws_audit[f"C{r3}"].font = Font(bold=True)
            ws_audit[f"E{r3}"] = f"=SUM(E4:E{r3-1})"
            ws_audit[f"E{r3}"].font = Font(bold=True)
            ws_audit[f"E{r3}"].number_format = "#,##0.00;(#,##0.00);\"-\""
            ws_audit[f"E{r3}"].border = top_double_bottom_border
            ws_audit[f"E{r3}"].alignment = Alignment(horizontal="right")
        else:
            ws_audit[f"B4"] = "No manual or automated adjustments recorded for this period."

        # Save to BytesIO
        output = io.BytesIO()
        wb.save(output)
        output.seek(0)
        return output
