"""Add RegulationImpact model

Revision ID: ba321e59f732
Revises: a7534b7235dc
Create Date: 2025-11-27 09:13:01.266889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'ba321e59f732'
down_revision = 'a7534b7235dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulation_impacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('regulation_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('impact_score', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('action_items', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulation_impacts_company_id'), 'regulation_impacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_regulation_impacts_regulation_id'), 'regulation_impacts', ['regulation_id'], unique=False)
    op.drop_table('transformation_adjustments')
    op.alter_column('alerts', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('alerts', 'message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alerts', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alerts', 'company_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('alerts', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('alerts', 'created_by',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('alerts', 'assigned_to',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_index(op.f('ix_alerts_regulation'), 'alerts', ['regulation'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_foreign_key(None, 'alerts', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'alerts', 'users', ['assigned_to'], ['id'])
    op.create_foreign_key(None, 'alerts', 'companies', ['company_id'], ['id'])
    op.alter_column('audit_logs', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.drop_column('audit_logs', 'entity_id')
    op.drop_column('audit_logs', 'entity_type')
    op.alter_column('balance_sheet_items', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('balance_sheet_items', 'balance_sheet_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('balance_sheet_items', 'account_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('balance_sheet_items', 'category',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.drop_index('ix_balance_sheet_items_balance_sheet_id', table_name='balance_sheet_items')
    op.drop_index('ix_balance_sheet_items_category', table_name='balance_sheet_items')
    op.drop_constraint(None, 'balance_sheet_items', type_='foreignkey')
    op.create_foreign_key(None, 'balance_sheet_items', 'balance_sheets', ['balance_sheet_id'], ['id'])
    op.alter_column('balance_sheets', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('balance_sheets', 'company_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index('ix_balance_sheets_company_id', table_name='balance_sheets')
    op.drop_index('ix_balance_sheets_period', table_name='balance_sheets')
    op.drop_column('balance_sheets', 'updated_at')
    op.alter_column('companies', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('companies', 'owner_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('companies', 'created_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('companies', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index('ix_companies_name', table_name='companies')
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_is_active'), 'companies', ['is_active'], unique=False)
    op.create_index(op.f('ix_companies_owner_id'), 'companies', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'companies', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'companies', 'users', ['created_by_id'], ['id'])
    op.alter_column('link_company_regulation', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('link_company_regulation', 'company_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('link_company_regulation', 'regulation_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('link_company_regulation', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('regulations', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('regulations', 'workflow_steps',
               existing_type=sa.TEXT(),
               type_=postgresql.JSON(astext_type=Text()),
               existing_nullable=True)
    op.alter_column('regulations', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('report_analyses', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('report_analyses', 'report_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index('ix_report_analyses_report_id', table_name='report_analyses')
    op.drop_index('ix_report_analyses_status', table_name='report_analyses')
    op.alter_column('report_comments', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('report_comments', 'report_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('report_comments', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('report_comments', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_index('ix_report_comments_report_id', table_name='report_comments')
    op.drop_index('ix_report_comments_user_id', table_name='report_comments')
    op.alter_column('report_templates', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('report_templates', 'created_by',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('report_templates', 'company_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('report_templates', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('reports', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('reports', 'submitted_by',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('reports', 'reviewed_by',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('reports', 'company_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('reports', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index('ix_reports_company_id', table_name='reports')
    op.drop_index('ix_reports_status', table_name='reports')
    op.drop_index('ix_reports_submitted_by', table_name='reports')
    op.alter_column('tax_rates', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('tenants', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('transformed_statements', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('transformed_statements', 'balance_sheet_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('transformed_statements', 'transformed_data',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('transformed_statements', 'transformation_rules_applied',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('ix_transformed_statements_balance_sheet_id', table_name='transformed_statements')
    op.drop_index('ix_transformed_statements_format_type', table_name='transformed_statements')
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('users', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('users', 'company_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'company_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.create_index('ix_transformed_statements_format_type', 'transformed_statements', ['format_type'], unique=False)
    op.create_index('ix_transformed_statements_balance_sheet_id', 'transformed_statements', ['balance_sheet_id'], unique=False)
    op.alter_column('transformed_statements', 'transformation_rules_applied',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    op.alter_column('transformed_statements', 'transformed_data',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=False)
    op.alter_column('transformed_statements', 'balance_sheet_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('transformed_statements', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('tenants', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('tax_rates', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.create_index('ix_reports_submitted_by', 'reports', ['submitted_by'], unique=False)
    op.create_index('ix_reports_status', 'reports', ['status'], unique=False)
    op.create_index('ix_reports_company_id', 'reports', ['company_id'], unique=False)
    op.alter_column('reports', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('reports', 'company_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('reports', 'reviewed_by',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('reports', 'submitted_by',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('reports', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('report_templates', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('report_templates', 'company_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('report_templates', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('report_templates', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.create_index('ix_report_comments_user_id', 'report_comments', ['user_id'], unique=False)
    op.create_index('ix_report_comments_report_id', 'report_comments', ['report_id'], unique=False)
    op.alter_column('report_comments', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('report_comments', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('report_comments', 'report_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('report_comments', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.create_index('ix_report_analyses_status', 'report_analyses', ['status'], unique=False)
    op.create_index('ix_report_analyses_report_id', 'report_analyses', ['report_id'], unique=False)
    op.alter_column('report_analyses', 'report_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('report_analyses', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('regulations', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('regulations', 'workflow_steps',
               existing_type=postgresql.JSON(astext_type=Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('regulations', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('link_company_regulation', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('link_company_regulation', 'regulation_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('link_company_regulation', 'company_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('link_company_regulation', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_index(op.f('ix_companies_owner_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_is_active'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.create_index('ix_companies_name', 'companies', ['name'], unique=False)
    op.alter_column('companies', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('companies', 'created_by_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('companies', 'owner_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('companies', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.add_column('balance_sheets', sa.Column('updated_at', sa.DATETIME(), nullable=False))
    op.create_index('ix_balance_sheets_period', 'balance_sheets', ['period'], unique=False)
    op.create_index('ix_balance_sheets_company_id', 'balance_sheets', ['company_id'], unique=False)
    op.alter_column('balance_sheets', 'company_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('balance_sheets', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_constraint(None, 'balance_sheet_items', type_='foreignkey')
    op.create_foreign_key(None, 'balance_sheet_items', 'balance_sheets', ['balance_sheet_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_balance_sheet_items_category', 'balance_sheet_items', ['category'], unique=False)
    op.create_index('ix_balance_sheet_items_balance_sheet_id', 'balance_sheet_items', ['balance_sheet_id'], unique=False)
    op.alter_column('balance_sheet_items', 'category',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('balance_sheet_items', 'account_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('balance_sheet_items', 'balance_sheet_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('balance_sheet_items', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.add_column('audit_logs', sa.Column('entity_type', sa.VARCHAR(), nullable=True))
    op.add_column('audit_logs', sa.Column('entity_id', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_regulation'), table_name='alerts')
    op.alter_column('alerts', 'assigned_to',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('alerts', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('alerts', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('alerts', 'company_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('alerts', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alerts', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('alerts', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.create_table('transformation_adjustments',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('balance_sheet_id', sa.NUMERIC(), nullable=False),
    sa.Column('balance_sheet_item_id', sa.NUMERIC(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=False),
    sa.Column('adjustment_amount', sa.NUMERIC(precision=15, scale=2), nullable=False),
    sa.Column('adjustment_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ifrs_category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['balance_sheet_id'], ['balance_sheets.id'], ),
    sa.ForeignKeyConstraint(['balance_sheet_item_id'], ['balance_sheet_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_regulation_impacts_regulation_id'), table_name='regulation_impacts')
    op.drop_index(op.f('ix_regulation_impacts_company_id'), table_name='regulation_impacts')
    op.drop_table('regulation_impacts')
    # ### end Alembic commands ###
