"""add_transformation_adjustments

Revision ID: cf2548374646
Revises: ba321e59f732
Create Date: 2025-11-27 13:35:53.920353

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'cf2548374646'
down_revision = 'ba321e59f732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transformation_adjustments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('balance_sheet_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('adjustment_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('adjustment_type', sa.String(length=10), nullable=False),
    sa.Column('ifrs_category', sa.String(length=100), nullable=True),
    sa.Column('balance_sheet_item_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['balance_sheet_id'], ['balance_sheets.id'], ),
    sa.ForeignKeyConstraint(['balance_sheet_item_id'], ['balance_sheet_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transformation_adjustments')
    # ### end Alembic commands ###
